name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git lfs install
          git checkout --orphan deploy-branch
          git add -A
          git commit -m "Deploy Streamlit Movie Application to Hugging Face"
          git push --force https://Baizid122:$HF_TOKEN@huggingface.co/spaces/Baizid122/MovieApplication deploy-branch:main
